name: Playwright E2E
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./.github/actions/setup/
    - name: Install wait-for
      run: npm install -g wait-port
    - name: Install Playwright Browsers
      run: npm playwright install --with-deps
    - name: Run Environment & test
      run: |
        npm run start &
        wait-port 3000
        sleep 60
        CICD=1 REPORT_FOLDER=current UI_SERVER=http://localhost:3000 npm run e2e:chrome
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: __report__/e2e/current
        retention-days: 30
